BEGIN {
S["am__EXEEXT_FALSE"]=""
S["am__EXEEXT_TRUE"]="#"
S["LTLIBOBJS"]=""
S["LIBOBJS"]=""
S["pangoft2_LIBS"]="-L/usr/local/Cellar/pango/1.44.7/lib -L/usr/local/Cellar/glib/2.62.4/lib -L/usr/local/opt/gettext/lib -L/usr/local/Cellar/harfbuzz/2.6.4/lib -L/usr/"\
"local/Cellar/fontconfig/2.13.1/lib -L/usr/local/opt/freetype/lib -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lintl -lharfbuzz -lfontconfig "\
"-lfreetype"
S["pangoft2_CFLAGS"]="-I/usr/local/Cellar/libffi/3.2.1/lib/libffi-3.2.1/include -I/usr/local/Cellar/pango/1.44.7/include/pango-1.0 -I/usr/local/Cellar/fribidi/1.0.8/inclu"\
"de/fribidi -I/usr/local/Cellar/cairo/1.16.0_2/include/cairo -I/usr/local/Cellar/pixman/0.38.4/include/pixman-1 -I/usr/local/Cellar/libpng/1.6.37/inc"\
"lude/libpng16 -I/usr/local/Cellar/glib/2.62.4/include -I/usr/local/Cellar/harfbuzz/2.6.4/include/harfbuzz -I/usr/local/Cellar/glib/2.62.4/include/gl"\
"ib-2.0 -I/usr/local/Cellar/glib/2.62.4/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.43/include -I/usr/local/Cell"\
"ar/graphite2/1.3.13/include -I/usr/local/Cellar/fontconfig/2.13.1/include -I/usr/local/opt/freetype/include/freetype2"
S["pangocairo_LIBS"]="-L/usr/local/Cellar/pango/1.44.7/lib -L/usr/local/Cellar/glib/2.62.4/lib -L/usr/local/opt/gettext/lib -L/usr/local/Cellar/harfbuzz/2.6.4/lib -L/usr/"\
"local/Cellar/cairo/1.16.0_2/lib -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lintl -lharfbuzz -lcairo"
S["pangocairo_CFLAGS"]="-I/usr/local/Cellar/libffi/3.2.1/lib/libffi-3.2.1/include -I/usr/local/Cellar/pango/1.44.7/include/pango-1.0 -I/usr/local/Cellar/fribidi/1.0.8/inclu"\
"de/fribidi -I/usr/local/Cellar/harfbuzz/2.6.4/include/harfbuzz -I/usr/local/Cellar/graphite2/1.3.13/include -I/usr/local/Cellar/cairo/1.16.0_2/inclu"\
"de/cairo -I/usr/local/Cellar/glib/2.62.4/include -I/usr/local/Cellar/glib/2.62.4/include/glib-2.0 -I/usr/local/Cellar/glib/2.62.4/lib/glib-2.0/inclu"\
"de -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.43/include -I/usr/local/Cellar/pixman/0.38.4/include/pixman-1 -I/usr/local/Cellar/fon"\
"tconfig/2.13.1/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/libpng/1.6.37/include/libpng16"
S["cairo_LIBS"]="-L/usr/local/Cellar/cairo/1.16.0_2/lib -lcairo"
S["cairo_CFLAGS"]="-I/usr/local/Cellar/libffi/3.2.1/lib/libffi-3.2.1/include -I/usr/local/Cellar/cairo/1.16.0_2/include/cairo -I/usr/local/Cellar/glib/2.62.4/include -"\
"I/usr/local/Cellar/glib/2.62.4/include/glib-2.0 -I/usr/local/Cellar/glib/2.62.4/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/C"\
"ellar/pcre/8.43/include -I/usr/local/Cellar/pixman/0.38.4/include/pixman-1 -I/usr/local/Cellar/fontconfig/2.13.1/include -I/usr/local/opt/freetype/i"\
"nclude/freetype2 -I/usr/local/Cellar/libpng/1.6.37/include/libpng16"
S["pango_LIBS"]="-L/usr/local/Cellar/pango/1.44.7/lib -L/usr/local/Cellar/glib/2.62.4/lib -L/usr/local/opt/gettext/lib -L/usr/local/Cellar/harfbuzz/2.6.4/lib -lpango"\
"-1.0 -lgobject-2.0 -lglib-2.0 -lintl -lharfbuzz"
S["pango_CFLAGS"]="-I/usr/local/Cellar/libffi/3.2.1/lib/libffi-3.2.1/include -I/usr/local/Cellar/pango/1.44.7/include/pango-1.0 -I/usr/local/Cellar/fribidi/1.0.8/inclu"\
"de/fribidi -I/usr/local/Cellar/cairo/1.16.0_2/include/cairo -I/usr/local/Cellar/pixman/0.38.4/include/pixman-1 -I/usr/local/Cellar/fontconfig/2.13.1"\
"/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/libpng/1.6.37/include/libpng16 -I/usr/local/Cellar/glib/2.62.4/include -I/u"\
"sr/local/Cellar/harfbuzz/2.6.4/include/harfbuzz -I/usr/local/Cellar/glib/2.62.4/include/glib-2.0 -I/usr/local/Cellar/glib/2.62.4/lib/glib-2.0/includ"\
"e -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.43/include -I/usr/local/Cellar/graphite2/1.3.13/include"
S["ICU_I18N_LIBS"]=""
S["ICU_I18N_CFLAGS"]=""
S["ICU_UC_LIBS"]=""
S["ICU_UC_CFLAGS"]=""
S["ENABLE_TRAINING_FALSE"]=""
S["ENABLE_TRAINING_TRUE"]="#"
S["HAVE_LIBARCHIVE_FALSE"]=""
S["HAVE_LIBARCHIVE_TRUE"]="#"
S["libarchive_LIBS"]=""
S["libarchive_CFLAGS"]=""
S["LEPTONICA_LIBS"]="-L/usr/local/Cellar/leptonica/1.78.0_1/lib -llept"
S["LEPTONICA_CFLAGS"]="-I/usr/local/Cellar/leptonica/1.78.0_1/include/leptonica"
S["HAVE_LIBCURL_FALSE"]="#"
S["HAVE_LIBCURL_TRUE"]=""
S["libcurl_LIBS"]="-lcurl"
S["libcurl_CFLAGS"]=""
S["PKG_CONFIG_LIBDIR"]=""
S["PKG_CONFIG_PATH"]=""
S["PKG_CONFIG"]="/usr/local/bin/pkg-config"
S["ASCIIDOC_FALSE"]=""
S["ASCIIDOC_TRUE"]="#"
S["have_xsltproc"]="true"
S["have_asciidoc"]="false"
S["LT_SYS_LIBRARY_PATH"]=""
S["OTOOL64"]=":"
S["OTOOL"]="otool"
S["LIPO"]="lipo"
S["NMEDIT"]="nmedit"
S["DSYMUTIL"]="dsymutil"
S["MANIFEST_TOOL"]=":"
S["RANLIB"]="ranlib"
S["ac_ct_AR"]="ar"
S["AR"]="ar"
S["DLLTOOL"]="false"
S["OBJDUMP"]="objdump"
S["LN_S"]="ln -s"
S["NM"]="/usr/bin/nm -B"
S["ac_ct_DUMPBIN"]=""
S["DUMPBIN"]=""
S["LD"]="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld"
S["FGREP"]="/usr/bin/grep -F"
S["am__fastdepCC_FALSE"]="#"
S["am__fastdepCC_TRUE"]=""
S["CCDEPMODE"]="depmode=gcc3"
S["ac_ct_CC"]="gcc"
S["CFLAGS"]="-g -O2"
S["CC"]="gcc"
S["LIBTOOL"]="$(SHELL) $(top_builddir)/libtool"
S["NO_TESSDATA_PREFIX_FALSE"]=""
S["NO_TESSDATA_PREFIX_TRUE"]="#"
S["VISIBILITY_FALSE"]=""
S["VISIBILITY_TRUE"]="#"
S["OPENCL_LDFLAGS"]=""
S["OPENCL_CPPFLAGS"]=""
S["USE_OPENCL_FALSE"]=""
S["USE_OPENCL_TRUE"]="#"
S["FRAMEWORK_OPENCL"]="-framework OpenCL"
S["TENSORFLOW_LIBS"]=""
S["TENSORFLOW_FALSE"]=""
S["TENSORFLOW_TRUE"]="#"
S["EGREP"]="/usr/bin/grep -E"
S["GREP"]="/usr/bin/grep"
S["CXXCPP"]="g++ -E"
S["OPENMP_CXXFLAGS"]=""
S["DISABLED_LEGACY_ENGINE_FALSE"]=""
S["DISABLED_LEGACY_ENGINE_TRUE"]="#"
S["MARCH_NATIVE_OPT_FALSE"]="#"
S["MARCH_NATIVE_OPT_TRUE"]=""
S["HAVE_SSE4_1_FALSE"]="#"
S["HAVE_SSE4_1_TRUE"]=""
S["HAVE_FMA_FALSE"]="#"
S["HAVE_FMA_TRUE"]=""
S["HAVE_AVX2_FALSE"]="#"
S["HAVE_AVX2_TRUE"]=""
S["HAVE_AVX_FALSE"]="#"
S["HAVE_AVX_TRUE"]=""
S["NOUNDEFINED"]=""
S["AM_LDFLAGS"]=""
S["ADD_RT_FALSE"]=""
S["ADD_RT_TRUE"]="#"
S["host_os"]="darwin19.3.0"
S["host_vendor"]="apple"
S["host_cpu"]="x86_64"
S["host"]="x86_64-apple-darwin19.3.0"
S["build_os"]="darwin19.3.0"
S["build_vendor"]="apple"
S["build_cpu"]="x86_64"
S["build"]="x86_64-apple-darwin19.3.0"
S["AM_CPPFLAGS"]=" -g -Wall -DDEBUG -pedantic -O0"
S["GRAPHICS_DISABLED_FALSE"]=""
S["GRAPHICS_DISABLED_TRUE"]="#"
S["OSX_FALSE"]=""
S["OSX_TRUE"]="#"
S["T_WIN_FALSE"]=""
S["T_WIN_TRUE"]="#"
S["GENERIC_VERSION"]="5.0.0"
S["GENERIC_RELEASE"]="5.0"
S["GENERIC_LIBRARY_NAME"]="tesseract"
S["GENERIC_LIBRARY_VERSION"]="5:0"
S["GENERIC_MICRO_VERSION"]="0"
S["GENERIC_MINOR_VERSION"]="0"
S["GENERIC_MAJOR_VERSION"]="5"
S["GENERIC_API_VERSION"]="5.0"
S["SED"]="/usr/bin/sed"
S["PACKAGE_DATE"]="10/29"
S["PACKAGE_YEAR"]="2018"
S["AM_BACKSLASH"]="\\"
S["AM_DEFAULT_VERBOSITY"]="1"
S["AM_DEFAULT_V"]="$(AM_DEFAULT_VERBOSITY)"
S["AM_V"]="$(V)"
S["am__fastdepCXX_FALSE"]="#"
S["am__fastdepCXX_TRUE"]=""
S["CXXDEPMODE"]="depmode=gcc3"
S["am__nodep"]="_no"
S["AMDEPBACKSLASH"]="\\"
S["AMDEP_FALSE"]="#"
S["AMDEP_TRUE"]=""
S["am__include"]="include"
S["DEPDIR"]=".deps"
S["am__untar"]="$${TAR-tar} xf -"
S["am__tar"]="$${TAR-tar} chof - \"$$tardir\""
S["AMTAR"]="$${TAR-tar}"
S["am__leading_dot"]="."
S["SET_MAKE"]=""
S["AWK"]="awk"
S["mkdir_p"]="$(MKDIR_P)"
S["MKDIR_P"]="config/install-sh -c -d"
S["INSTALL_STRIP_PROGRAM"]="$(install_sh) -c -s"
S["STRIP"]="strip"
S["install_sh"]="${SHELL} /Users/user/dev/nanet/tesseract/tesseract/config/install-sh"
S["MAKEINFO"]="${SHELL} /Users/user/dev/nanet/tesseract/tesseract/config/missing makeinfo"
S["AUTOHEADER"]="${SHELL} /Users/user/dev/nanet/tesseract/tesseract/config/missing autoheader"
S["AUTOMAKE"]="${SHELL} /Users/user/dev/nanet/tesseract/tesseract/config/missing automake-1.16"
S["AUTOCONF"]="${SHELL} /Users/user/dev/nanet/tesseract/tesseract/config/missing autoconf"
S["ACLOCAL"]="${SHELL} /Users/user/dev/nanet/tesseract/tesseract/config/missing aclocal-1.16"
S["VERSION"]="5.0.0-alpha-630-gce019"
S["PACKAGE"]="tesseract"
S["CYGPATH_W"]="echo"
S["am__isrc"]=""
S["INSTALL_DATA"]="${INSTALL} -m 644"
S["INSTALL_SCRIPT"]="${INSTALL}"
S["INSTALL_PROGRAM"]="${INSTALL}"
S["OBJEXT"]="o"
S["EXEEXT"]=""
S["ac_ct_CXX"]="g++"
S["CPPFLAGS"]=" -I/usr/local/Cellar/leptonica/1.78.0_1/include/leptonica"
S["LDFLAGS"]=""
S["CXXFLAGS"]="-g -O2 -std=c++17"
S["CXX"]="g++"
S["target_alias"]=""
S["host_alias"]=""
S["build_alias"]=""
S["LIBS"]=""
S["ECHO_T"]=""
S["ECHO_N"]=""
S["ECHO_C"]="\\c"
S["DEFS"]="-DHAVE_CONFIG_H"
S["mandir"]="${datarootdir}/man"
S["localedir"]="${datarootdir}/locale"
S["libdir"]="${exec_prefix}/lib"
S["psdir"]="${docdir}"
S["pdfdir"]="${docdir}"
S["dvidir"]="${docdir}"
S["htmldir"]="${docdir}"
S["infodir"]="${datarootdir}/info"
S["docdir"]="${datarootdir}/doc/${PACKAGE_TARNAME}"
S["oldincludedir"]="/usr/include"
S["includedir"]="${prefix}/include"
S["localstatedir"]="${prefix}/var"
S["sharedstatedir"]="${prefix}/com"
S["sysconfdir"]="${prefix}/etc"
S["datadir"]="${datarootdir}"
S["datarootdir"]="${prefix}/share"
S["libexecdir"]="${exec_prefix}/libexec"
S["sbindir"]="${exec_prefix}/sbin"
S["bindir"]="${exec_prefix}/bin"
S["program_transform_name"]="s,x,x,"
S["prefix"]="/usr/local"
S["exec_prefix"]="${prefix}"
S["PACKAGE_URL"]="https://github.com/tesseract-ocr/tesseract/"
S["PACKAGE_BUGREPORT"]="https://github.com/tesseract-ocr/tesseract/issues"
S["PACKAGE_STRING"]="tesseract 5.0.0-alpha-630-gce019"
S["PACKAGE_VERSION"]="5.0.0-alpha-630-gce019"
S["PACKAGE_TARNAME"]="tesseract"
S["PACKAGE_NAME"]="tesseract"
S["PATH_SEPARATOR"]=":"
S["SHELL"]="/bin/sh"
S["am__quote"]=""
  for (key in S) S_is_set[key] = 1
  FS = ""

}
{
  line = $ 0
  nfields = split(line, field, "@")
  substed = 0
  len = length(field[1])
  for (i = 2; i < nfields; i++) {
    key = field[i]
    keylen = length(key)
    if (S_is_set[key]) {
      value = S[key]
      line = substr(line, 1, len) "" value "" substr(line, len + keylen + 3)
      len += length(value) + length(field[++i])
      substed = 1
    } else
      len += 1 + keylen
  }

  print line
}

